movie/movie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root = settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root = settings.MEDIA_ROOT)

movie/movieapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie/movieapp/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):

    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie/movieapp/forms.py
from django import forms
from django.db import models
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movie/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,'movie.html',{'result':movie})

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'addmovie.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=="POST":
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie/templates/addmovie.html
{% extends 'base.html' %}
{% block body %}
    <form method="POST" enctype="multipart/form-data">
    <br>
        {% csrf_token %}
        <input type="text" placeholder="Name of the Movie" name="name">
        <br>
        <input type="text" placeholder="Enter the Description" name="desc">
        <br>
        <input type="text" placeholder="Enter the Year" name="year">
        <br>
        <input type="file" placeholder="Select the Image" name="img">
        <br>
        <input type="submit">

    </form>
{% endblock %}

movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        Online Movie Store
    </a>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Are You Want to Delete this Movie</h3>
        <input type="submit">
    </form>
{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% block body %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

movie/templates/index.html
{% extends 'base.html' %}
{% block body %}

<br>
<h2 >Movie List</h2>
    <br>
    <button class="btn btn-primary" style="color: white" ><a href="{% url 'movieapp:add_movie' %}" style="text-decoration: none;color: white">Add Movie</a> </button>
    <br>
    <br>

    <div class="container">

        <div class="row">
            {% for i in movie_list %}
            <div class="col-md-3" style="margin-right: 40px;margin-bottom: 20px">
            <div class="card" style="width: 18rem; height: 35rem; padding: 20px">
            <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" width="70px" height="250px">
            <div class="card-body">
            <h5 class="card-title">{{ i.name }}</h5>
            <p class="card-text">{{ i.desc }}</p>
            <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go To the Page</a>
             </div>
            </div>
        </div>
            {% endfor %}
            </div>

    </div>

{% endblock %}

movie/templates/movie.html
{% extends 'base.html' %}
{% block body %}
<br>
    <style>
        .a11{
            margin-left: 20px;
        }
    </style>
    <div class="a11">
<h1 style="margin-left: 175px">Movie Details</h1>
    <br>
    <div class="all" style="justify-content: center">
        <div class="image" style="margin-right: 100px">
        <img src="{{ result.img.url }}" height="200px" width="200px">
    </div>
<div class="m1" style="margin-right: 100px">
    <div class="mname"><strong>Movie Name:</strong> {{ result.name }}</div>
    <br>
    <div class="mname"><strong>Movie Detail:</strong> {{ result.desc }}</div>
    <br>
    <div class="mname"><strong>Year of Release: </strong>{{ result.year }}</div><br>
    <a class="btn btn-warning" href="{% url 'movieapp:update' result.id %}" style="margin-right: 20px">Update</a>
     <a class="btn btn-danger" href="{% url 'movieapp:delete' result.id %}">Delete</a>
</div>

    </div>

    </div>

{% endblock %}